<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.gitcode.framework.parent</groupId>
        <artifactId>gitcode-framework-parent</artifactId>
        <version>1.0.3</version>
    </parent>

    <groupId>com.gitcode.grouprepo.business</groupId>
    <artifactId>grouprepo-business</artifactId>
    <version>1.2.73</version>
    <packaging>pom</packaging>

    <modules>
        <module>common</module>
        <module>feign-api</module>
        <module>service</module>
    </modules>
    <properties>
        <service.version>${version}</service.version>
        <versions-maven-plugin.version>2.2</versions-maven-plugin.version>
        <java.version>1.8</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <easyexcel.version>4.0.1</easyexcel.version>
        <huawei.obs.version>3.23.3</huawei.obs.version>
        <gitcode-common.version>1.0.5</gitcode-common.version>
        <gitcode-base-common.version>1.0.13</gitcode-base-common.version>
        <gitcode.version>1.0.0</gitcode.version>
        <hubservice.version>1.2.94</hubservice.version>
        <usercenter.version>1.2.6</usercenter.version>
        <search-service.version>1.0.4</search-service.version>
        <gitcode-access-control.version>1.0.10</gitcode-access-control.version>
        <gitcode-nacos-endpoint.version>1.0.0</gitcode-nacos-endpoint.version>
        <notify-feign-api.version>1.0.3</notify-feign-api.version>
        <gitcode-syncservice-feign-api.version>1.0.5</gitcode-syncservice-feign-api.version>
        <audit-service-business-feign-api.version>1.0.2</audit-service-business-feign-api.version>
        <operation-feign-api.version>1.0.0</operation-feign-api.version>
        <huawei-extend-feign-api.version>1.0.7</huawei-extend-feign-api.version>
        <gitcode-audit-service.version>1.0.8</gitcode-audit-service.version>
        <audit-service-open-feign-api.version>1.0.8</audit-service-open-feign-api.version>
    </properties>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.huaweicloud</groupId>
                <artifactId>esdk-obs-java-bundle</artifactId>
                <version>${huawei.obs.version}</version>
            </dependency>
            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>easyexcel-core</artifactId>
                <version>${easyexcel.version}</version>
            </dependency>

            <dependency>
                <groupId>com.gitcode.grouprepo.business.common</groupId>
                <artifactId>common</artifactId>
                <version>${service.version}</version>
            </dependency>
            <dependency>
                <groupId>com.gitcode.grouprepo.business.feign</groupId>
                <artifactId>feign-api</artifactId>
                <version>${service.version}</version>
            </dependency>
            <dependency>
                <groupId>com.gitcode.common</groupId>
                <artifactId>base-common</artifactId>
                <version>${gitcode-base-common.version}</version>
            </dependency>
            <dependency>
                <groupId>com.gitcode.feign.common</groupId>
                <artifactId>gitcode-feign-common</artifactId>
                <version>${gitcode-common.version}</version>
            </dependency>
            <dependency>
                <groupId>com.gitcode.hubservice</groupId>
                <artifactId>gitcode-hubservice-feign-api</artifactId>
                <version>${hubservice.version}</version>
            </dependency>
            <dependency>
                <groupId>com.gitcode.usercenter</groupId>
                <artifactId>usercenter-feign-api</artifactId>
                <version>${usercenter.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>com.gitcode</groupId>
                        <artifactId>gitcode-common</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>com.gitcode.feign.common</groupId>
                        <artifactId>gitcode-feign-common</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>com.gitcode.feign.system</groupId>
                <artifactId>gitcode-feign-system-api</artifactId>
                <version>1.0.2</version>
            </dependency>
            <dependency>
                <groupId>com.gitcode</groupId>
                <artifactId>search-service-feign-api</artifactId>
                <version>${search-service.version}</version>
            </dependency>
            <dependency>
                <groupId>com.gitcode.ac</groupId>
                <artifactId>access-control-authorize</artifactId>
                <version>${gitcode-access-control.version}</version>
            </dependency>
            <dependency>
                <groupId>com.gitcode.framework.nacos</groupId>
                <artifactId>gitcode-nacos-endpoint</artifactId>
                <version>${gitcode-nacos-endpoint.version}</version>
            </dependency>
            <dependency>
                <groupId>com.gitcode.notify</groupId>
                <artifactId>notify-feign-api</artifactId>
                <version>${notify-feign-api.version}</version>
            </dependency>
            <dependency>
                <groupId>com.gitcode.syncservice</groupId>
                <artifactId>gitcode-syncservice-feign-api</artifactId>
                <version>${gitcode-syncservice-feign-api.version}</version>
            </dependency>
            <dependency>
                <groupId>com.gitcode.ac</groupId>
                <artifactId>access-control-feign-api</artifactId>
                <version>${gitcode-access-control.version}</version>
            </dependency>
            <dependency>
                <groupId>com.gitcode.audit.service</groupId>
                <artifactId>audit-service-business-feign-api</artifactId>
                <version>${audit-service-business-feign-api.version}</version>
            </dependency>
            <dependency>
                <groupId>com.gitcode.operation</groupId>
                <artifactId>operation-feign-api</artifactId>
                <version>${operation-feign-api.version}</version>
            </dependency>
            <dependency>
                <groupId>com.gitcode</groupId>
                <artifactId>huawei-extend-feign-api</artifactId>
                <version>${huawei-extend-feign-api.version}</version>
            </dependency>
            <dependency>
                <groupId>com.gitcode.audit.service</groupId>
                <artifactId>audit-service-open-feign-api</artifactId>
                <version>${gitcode-audit-service.version}</version>
            </dependency>
            <dependency>
                <groupId>com.gitcode.audit.service</groupId>
                <artifactId>audit-service-common</artifactId>
                <version>${gitcode-audit-service.version}</version>
            </dependency>
            <dependency>
                <groupId>com.gitcode.audit.service</groupId>
                <artifactId>audit-service-open-feign-api</artifactId>
                <version>${audit-service-open-feign-api.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <!-- 远程拉取代码仓库 vpn-->
    <repositories>
        <repository>
            <id>maven-public</id>
            <url>https://maven.aliyun.com/repository/public</url>
        </repository>
        <repository>
            <id>huaweicloud</id>
            <name>Huawei Cloud Maven Repository</name>
            <url>https://repo.huaweicloud.com/repository/maven/</url>
        </repository>
        <repository>
            <id>HuaweiCloudSDK</id>
            <url>https://mirrors.huaweicloud.com/repository/maven/huaweicloudsdk/</url>
            <releases>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>maven-releases</id>
            <url>https://repo.gitcode.com/repository/maven-releases/</url>
        </repository>
        <repository>
            <id>maven-snapshot</id>
            <url>https://repo.gitcode.com/repository/maven-snapshots/</url>
        </repository>
    </repositories>

    <distributionManagement>
        <repository>
            <id>maven-releases</id>
            <url>http://repo.gitcode.com/repository/maven-releases/</url>
        </repository>
        <snapshotRepository>
            <id>maven-snapshots</id>
            <name>nexus SNAPSHOT</name>
            <url>https://repo.gitcode.com/repository/maven-snapshots/</url>
        </snapshotRepository>
    </distributionManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>versions-maven-plugin</artifactId>
                <version>${versions-maven-plugin.version}</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                    <encoding>UTF-8</encoding>
                </configuration>
            </plugin>
            <!--<plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${spring-boot.version}</version>
                <configuration>
                    <mainClass>com.gitcode.pipeline.service.PipelineServiceApplication</mainClass>
                    <skip>true</skip>
                </configuration>
                <executions>
                    <execution>
                        <id>repackage</id>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>-->
        </plugins>
    </build>
</project>